# Generated by Django 5.0.6 on 2024-07-08 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Des', models.TextField()),
                ('Date', models.DateField()),
                ('Image', models.ImageField(upload_to='pictures')),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('E_mail', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='serch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Maritial_status', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=20)),
                ('age', models.IntegerField()),
                ('age1', models.IntegerField()),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Sikh', 'Sikh'), ('Muslims', 'Muslims'), ('Christians', 'Christians'), ('Any', 'Any')], max_length=30)),
                ('education', models.CharField(choices=[('CFA (Chatared Financial Analyst)', 'CFA (Chatared Financial Analyst)'), ('CA (Chatared Accountant)', 'CA Chatared Accountant'), ('ICWA', 'ICWA'), ('Integrated P.G.', 'Integrated P.G.'), ('M.Arch.(Architecture)', 'M.Arch.(Architecture)'), ('M.Ed.(Education)', 'M.Ed.(Education)')], max_length=100)),
                ('occupation', models.CharField(choices=[('Media', ' Media '), ('Agriculture', 'Agriculture'), ('Architecture & Design', 'Architecture & Design'), ('Artists', 'Artists'), ('Animators & Web Designers', 'Animators & Web Designers'), ('Banking', 'Banking'), ('Insurance & Finacial Services', 'Insurance & Finacial Services'), ('Beauty', 'Beauty'), ('Fashion Designers', 'Fashion Designers'), ('Export & Import', 'Export & Import'), ('Govt. Employee', 'Govt. Employee'), ('Finance & Accounts', 'Finance & Accounts'), ('Healthcare', 'Healthcare'), ('Doctors', 'Doctors'), ('Engineer', 'Engineer'), ('Advocate', 'Advocate'), ('Merchant Navy', 'Merchant Navy'), ('Pvt. Job', 'Pvt. Job'), ('Business', 'Business')], max_length=100)),
            ],
            options={
                'db_table': 'serch',
            },
        ),
        migrations.CreateModel(
            name='showvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=300)),
                ('video', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'showvideo',
            },
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pictures')),
                ('name', models.CharField(max_length=100)),
                ('Wedding_Date', models.DateField()),
                ('Title', models.CharField(max_length=20)),
                ('Des', models.TextField()),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='searchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic1', models.ImageField(default='', upload_to='pictures/')),
                ('Pic2', models.ImageField(default='', upload_to='pictures/')),
                ('name', models.CharField(max_length=100)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('Maritial_status', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField()),
                ('religion', models.CharField(default='', max_length=30)),
                ('education', models.CharField(default='', max_length=100)),
                ('occupation', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('profileby', models.CharField(default='', max_length=50)),
                ('complexion', models.CharField(default='', max_length=30)),
                ('height', models.CharField(default='', max_length=20)),
                ('weight', models.CharField(default='', max_length=20)),
                ('approval', models.CharField(default='non_approval', max_length=20)),
                ('slist', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'searchs',
            },
        ),
        migrations.CreateModel(
            name='shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dd', to='website.searchs')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shortlist',
            },
        ),
    ]
