# Generated by Django 5.0.6 on 2024-07-11 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='searchs',
            table='Searchs',
        ),
        migrations.CreateModel(
            name='ViewedSearchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('searchs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.searchs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ViewedSearchs',
            },
        ),
    ]
