# Generated by Django 5.0.6 on 2024-07-11 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_shortlist_shortlisted_alter_searchs_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viewedsearchs',
            table=None,
        ),
    ]
