# Generated by Django 5.0.6 on 2024-07-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_viewedsearchs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viewedsearchs',
            table='ViewedSearchs',
        ),
    ]
