# Generated by Django 5.0.6 on 2024-07-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_viewedsearchs_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shortlist',
        ),
    ]
