# Generated by Django 4.0 on 2022-05-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0015_rename_shortlist_shortlist_slist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
